#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 007: Update Controller and Prisma for Evolution API

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/malone/evo-api-ghl"
cd "$PROJECT_DIR"

# Check for required files
echo "Checking prerequisites..."

if [ ! -f "package.json" ]; then
    echo -e "${RED}Error: package.json not found${NC}"
    exit 1
fi

if [ ! -f "prisma/schema.prisma" ]; then
    echo -e "${RED}Error: prisma/schema.prisma not found${NC}"
    exit 1
fi

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
fi

# Generate Prisma client
echo "Generating Prisma client..."
npx prisma generate

# Verify TypeScript compilation (dry run)
echo "Checking TypeScript compilation..."
if npx tsc --noEmit 2>&1 | head -5; then
    echo -e "${GREEN}TypeScript check passed${NC}"
else
    echo -e "${YELLOW}Warning: TypeScript has some issues (may be expected before implementation)${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: Evolution API → GoHighLevel Integration"
echo "Spec: 007 - Update Controller and Prisma for Evolution API"
echo ""
echo "Files to modify:"
echo "  - src/ghl/ghl.controller.ts"
echo "  - src/prisma/prisma.service.ts"
echo ""
echo "Key changes:"
echo "  - Remove @green-api/greenapi-integration dependencies"
echo "  - Update instance lookups from BigInt idInstance to string instanceName"
echo "  - Update CreateInstanceDto for Evolution API fields"
echo "  - Replace GreenApiLogger with NestJS Logger"
echo ""
echo "To run the development server:"
echo "  npm run start"
echo ""
echo "To check TypeScript compilation:"
echo "  npx tsc --noEmit"
echo ""
