#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 005: Update GHL Service for Evolution API

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 005-update-ghl-service-for-evolution-api"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/malone/evo-api-ghl"
cd "$PROJECT_DIR"

echo ""
echo "Checking prerequisites..."

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Check if Prisma client is generated
if [ ! -d "node_modules/.prisma" ]; then
    echo -e "${YELLOW}Generating Prisma client...${NC}"
    npx prisma generate
fi

echo -e "${GREEN}Prerequisites check complete${NC}"

# ============================================
# VERIFY DEPENDENCIES FROM OTHER SPECS
# ============================================

echo ""
echo "Verifying dependencies from other specs..."

# Check if Evolution API client exists (from spec 002)
if [ ! -f "src/evolution/evolution-api.client.ts" ]; then
    echo -e "${RED}WARNING: Evolution API client not found at src/evolution/evolution-api.client.ts${NC}"
    echo -e "${YELLOW}This spec depends on spec 002. Ensure it's been merged first.${NC}"
fi

# Check if Evolution webhook types exist (from spec 004)
if [ ! -f "src/ghl/types/evolution-webhook.types.ts" ]; then
    echo -e "${RED}WARNING: Evolution webhook types not found at src/ghl/types/evolution-webhook.types.ts${NC}"
    echo -e "${YELLOW}This spec depends on spec 004. Ensure it's been merged first.${NC}"
fi

# ============================================
# BUILD CHECK
# ============================================

echo ""
echo "Running TypeScript build check..."

if npm run build 2>/dev/null; then
    echo -e "${GREEN}TypeScript build successful${NC}"
else
    echo -e "${YELLOW}Build has errors - expected before implementation${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Spec 005"
echo "========================================"
echo ""
echo "Files to Modify:"
echo "  - src/ghl/ghl.service.ts"
echo "  - src/ghl/ghl.module.ts"
echo ""
echo "Pattern Reference Files:"
echo "  - src/evolution/evolution-api.client.ts"
echo "  - src/ghl/ghl.transformer.ts"
echo "  - src/ghl/types/evolution-webhook.types.ts"
echo ""
echo "Key Tasks:"
echo "  1. Remove GREEN-API SDK imports"
echo "  2. Add EvolutionApiClient import"
echo "  3. Replace GreenApiLogger with NestJS Logger"
echo "  4. Rename methods (createGreenApiInstanceForUser -> createEvolutionInstanceForUser)"
echo "  5. Update webhook handling for Evolution format"
echo "  6. Update message sending to use Evolution API"
echo "  7. Import EvolutionModule in GhlModule"
echo ""
echo "Run 'npm run start:dev' to start the development server"
echo ""
