#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 008: Update Dependencies and Documentation

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 008 - Update Dependencies and Documentation"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Change to project root
cd "$(dirname "$0")/../../.."
PROJECT_ROOT=$(pwd)
echo "Project root: $PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Running pre-flight checks..."

# Check if node is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed. Please install Node.js 20+${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo -e "${YELLOW}Warning: Node.js version is $NODE_VERSION, recommended is 20+${NC}"
fi
echo -e "${GREEN}Node.js $(node -v) found${NC}"

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm $(npm -v) found${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

npm install

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Dependencies installed successfully${NC}"
else
    echo -e "${RED}Failed to install dependencies${NC}"
    exit 1
fi

# ============================================
# CHECK DATABASE (Optional for this task)
# ============================================

echo ""
echo "Checking database configuration..."

if [ -f ".env" ]; then
    if grep -q "DATABASE_URL" .env; then
        echo -e "${GREEN}DATABASE_URL found in .env${NC}"
    else
        echo -e "${YELLOW}Warning: DATABASE_URL not found in .env${NC}"
    fi
else
    echo -e "${YELLOW}Warning: .env file not found. Copy from .env.example${NC}"
fi

# ============================================
# BUILD PROJECT
# ============================================

echo ""
echo "Building project..."

npm run build

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Project built successfully${NC}"
else
    echo -e "${RED}Build failed${NC}"
    exit 1
fi

# ============================================
# START SERVICES (Optional)
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "This task is primarily about updating dependencies and documentation."
echo "No services need to be running for this task."
echo ""
echo "To start the NestJS server for verification:"
echo "  npm run start:dev"
echo ""
echo "Service URL:"
echo "  Main Service: http://localhost:3000"
echo ""
echo "Key files to modify:"
echo "  - package.json (metadata and dependencies)"
echo "  - README.md (rebrand to Evolution API)"
echo "  - README.ru.md (Russian version)"
echo "  - src/webhooks/guards/greenapi-webhook.guard.ts (delete)"
echo "  - Multiple source files (remove GREEN-API references)"
echo ""
echo "Run 'npm run start:dev' to verify changes work correctly."
echo ""
