#!/bin/bash

# Auto-Build Environment Setup
# Spec: 004 - Update Message Transformer for Evolution API
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 004 - Update Message Transformer"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/malone/evo-api-ghl"
cd "$PROJECT_DIR"

# Check for required files
echo ""
echo "Checking prerequisites..."

if [ ! -f "package.json" ]; then
    echo -e "${RED}Error: package.json not found${NC}"
    exit 1
fi

if [ ! -f ".env" ] && [ -f ".env.example" ]; then
    echo -e "${YELLOW}Warning: .env file not found. Copy from .env.example if needed.${NC}"
fi

# Install dependencies if node_modules doesn't exist
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
fi

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting NestJS backend service..."

# Start the NestJS development server in background
npm run start:dev &
BACKEND_PID=$!

# Wait for backend to be ready
wait_for_service 3000 "NestJS Backend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend API: http://localhost:3000"
echo ""
echo "Process IDs:"
echo "  Backend PID: $BACKEND_PID"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID"
echo ""
echo "========================================"
echo "Ready to implement Spec 004"
echo "========================================"
