#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 003: Evolution API Webhook Handler

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 003 - Evolution API Webhook Handler"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/malone/evo-api-ghl"
cd "$PROJECT_DIR"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing npm dependencies...${NC}"
    npm install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# Check if Prisma client is generated
if [ ! -d "node_modules/.prisma" ]; then
    echo -e "${YELLOW}Generating Prisma client...${NC}"
    npx prisma generate
else
    echo -e "${GREEN}Prisma client already generated${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Check if database is needed (using docker-compose)
if [ -f "docker-compose.yml" ]; then
    echo "Starting database via docker-compose..."
    docker-compose up -d db 2>/dev/null || echo -e "${YELLOW}Docker db service not available or already running${NC}"
fi

# Start NestJS backend in development mode
echo "Starting NestJS backend..."
npm run start:dev &
BACKEND_PID=$!

# Wait for backend to be ready
wait_for_service 3000 "Backend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Backend:  http://localhost:3000"
echo ""
echo "Webhook Endpoints:"
echo "  Evolution API: POST http://localhost:3000/webhooks/evolution"
echo "  GHL:           POST http://localhost:3000/webhooks/ghl"
echo "  Workflow:      POST http://localhost:3000/webhooks/workflow-action"
echo ""
echo "To stop the backend: kill $BACKEND_PID"
echo ""
