#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: Evolution API HTTP Client Service

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/malone/evo-api-ghl"
cd "$PROJECT_DIR"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo "Checking dependencies..."
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# DATABASE CHECK (Optional)
# ============================================

echo ""
echo "Checking database..."
if [ -f ".env" ]; then
    echo "Running Prisma generate..."
    npx prisma generate
    echo -e "${GREEN}Prisma client generated${NC}"
else
    echo -e "${YELLOW}Warning: .env file not found. Copy .env.example to .env and configure.${NC}"
fi

# ============================================
# START MAIN SERVICE (if needed)
# ============================================

echo ""
echo "Note: For this task (Evolution API HTTP Client), you don't need to run the service."
echo "The implementation is a standalone module that will be tested via compilation."
echo ""
echo "If you need to test the full application, run:"
echo "  npm run start:dev"
echo ""

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project Type: Single NestJS Backend"
echo "Project Path: $PROJECT_DIR"
echo ""
echo "Files to Create:"
echo "  - src/evolution/evolution-api.types.ts"
echo "  - src/evolution/evolution-api.client.ts"
echo "  - src/evolution/evolution.module.ts"
echo ""
echo "Useful Commands:"
echo "  npm run build       - Compile TypeScript"
echo "  npm run start:dev   - Start in development mode"
echo "  npm run lint        - Run linter"
echo ""
echo "Patterns to Reference:"
echo "  - src/ghl/ghl.service.ts (axios HTTP client pattern)"
echo "  - src/prisma/prisma.module.ts (NestJS module pattern)"
echo ""
